project:
  type: website
  output-dir: docs

website:
  
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Robotic Strip Cropping"
        contents:
          - index.qmd
      - section: "Biodiversity"
        contents:
          - biodiversity.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

